name: Minimal API App Build and Deploy 

description: "Build and deploy Minimal API App"

inputs:
  AZURE_TENANT_ID:
    required: true
  AZURE_SUBSCRIPTION_ID:
    required: true
  AZURE_CLIENT_ID:
    required: true
  RESOURCE_NAME:
    required: true

runs:
  using: "composite"
  jobs:
    build:
      runs-on: windows-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3

        - name: Setup DotNet 8 Environment
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.x'

        - name: 'Build with dotnet'
          run: |
            cd '.\NJDOT.APIs.MinimalAPI'
            dotnet build --configuration Release
            dotnet publish -c Release  --output ./output

        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v3
          with:
            name: minimalapi-app
            path: .\NJDOT.APIs.MinimalAPI\output

    deploy:
      runs-on: windows-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      permissions:
        id-token: write #This is required for requesting the JWT

      steps:
        - name: Download artifact from build job
            uses: actions/download-artifact@v3
            with:
              name: minimalapi-app
        
        - name: Login to Azure
            uses: azure/login@v1
            with:
              tenant-id: ${{ inputs.AZURE_TENANT_ID }}
              subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
              client-id: ${{ inputs.AZURE_CLIENT_ID }}

        - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: '${{ inputs.RESOURCE_NAME }}minimalapi'
              slot-name: 'production'
              package: .
